on: [push]
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  version_tag:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            README.md
            package.json

      - name: Get version
        id: version
        uses: williamrjackson/upm_version_increment_action@v1.8
        with: 
          path: package.json
          key: version
      - name: Get the output time
        run: echo "The version is ${{ steps.version.outputs.value }}"
      - name: tag
        run: git -a tag v${{ steps.version.outputs.value }} -m "Tag with version"
      - name: push
        run: git push origin v${{ steps.version.outputs.value }}
