on: [push]
env:
  GITHUB_TOKEN: ${{ github.token }}
permissions: write-all

jobs:
  version_tag:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            README.md
            package.json

      - name: Get version
        id: version
        uses: williamrjackson/upm_version_increment_action@v1.99996
        with: 
          path: package.json
          increment: patch
      - name: gitconfig
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: commit changes
        run: |
          git add .
          git commit -m "[skip ci] automated version increment"
      - name: tag
        run: git tag -a -m "Tag with version" v${{ steps.version.outputs.value }}
      - name: push
        run: git push --follow-tags
