on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            README.md
            package.json
      - name: increment action step
        id: versionupdate
        uses: williamrjackson/upm_version_increment_action@v1.6
      - name: Get the output time
        run: echo "The new version is ${{ steps.versionupdate.outputs.new-version }}"
