on: [push]
env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  version_tag:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            README.md
            package.json

      - name: Get version
        id: version
        uses: williamrjackson/upm_version_increment_action@v1.8
        with: 
          path: package.json
          key: version
      - name: log
        run: echo "The version is ${{ steps.version.outputs.value }}"
      - name: gitconfig
        run: git config user.name "${GITHUB_ACTOR}"
            git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: tag
        run: git tag -a -m "Tag with version" v${{ steps.version.outputs.value }}
      - name: push
        run: git push --follow-tags
