on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Check out files
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            README.md
            package.json
      - name: Get version
        id: version
        uses: williamrjackson/upm_version_increment_action@v1.8
        with: 
          path: package.json
          key: version
      - name: Get the output time
        run: echo "The version is ${{ steps.version.outputs.value }}"
      - name: push tag
        uses: actions-ecosystem/action-push-tag@v1
        with:
          tag: ${{ steps.version.outputs.value }}
          message: 'Tag with version'

